resources:
   - nginx-deployment.yaml
   - service.yaml

commonLabels:
  web: nginx
  owner: oktay

commonAnnotations:
  sidecar.istio.io/inject: true

namePrefix: test-

nameSuffix: -dev

replicas:
- name: nginx
  count: 5

images:
- name: nginx
  newTag: 1.8.0

#patches:
#- path: patch.yaml
